//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/game2.proto
namespace game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Value")]
  public partial class Value : global::ProtoBuf.IExtensible
  {
    public Value() {}
    
    private game.Value.Datatype _datatype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"datatype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public game.Value.Datatype datatype
    {
      get { return _datatype; }
      set { _datatype = value; }
    }
    private string _strValue = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"strValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strValue
    {
      get { return _strValue; }
      set { _strValue = value; }
    }
    private int _int32Value = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"int32Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int int32Value
    {
      get { return _int32Value; }
      set { _int32Value = value; }
    }
    private uint _uint32Value = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uint32Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uint32Value
    {
      get { return _uint32Value; }
      set { _uint32Value = value; }
    }
    private long _int64Value = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"int64Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long int64Value
    {
      get { return _int64Value; }
      set { _int64Value = value; }
    }
    private ulong _uint64Value = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uint64Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uint64Value
    {
      get { return _uint64Value; }
      set { _uint64Value = value; }
    }
    private double _doubleValue = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"doubleValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double doubleValue
    {
      get { return _doubleValue; }
      set { _doubleValue = value; }
    }
    private float _floatValue = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"floatValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float floatValue
    {
      get { return _floatValue; }
      set { _floatValue = value; }
    }
    private bool _boolValue = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"boolValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool boolValue
    {
      get { return _boolValue; }
      set { _boolValue = value; }
    }
    private byte[] _bytesValue = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"bytesValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] bytesValue
    {
      get { return _bytesValue; }
      set { _bytesValue = value; }
    }
    private game.ValueMap _dictionary = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"dictionary", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public game.ValueMap dictionary
    {
      get { return _dictionary; }
      set { _dictionary = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Datatype")]
    public enum Datatype
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=-1)]
      NONE = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRING", Value=0)]
      STRING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INT32", Value=1)]
      INT32 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UINT32", Value=2)]
      UINT32 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INT64", Value=3)]
      INT64 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UINT64", Value=4)]
      UINT64 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DOUBLE", Value=5)]
      DOUBLE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLOAT", Value=6)]
      FLOAT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOOL", Value=7)]
      BOOL = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BYTES", Value=8)]
      BYTES = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DICTIONARY", Value=9)]
      DICTIONARY = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ValuePair")]
  public partial class ValuePair : global::ProtoBuf.IExtensible
  {
    public ValuePair() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private game.Value _value = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public game.Value value
    {
      get { return _value; }
      set { _value = value; }
    }
    private readonly global::System.Collections.Generic.List<game.Value> _values = new global::System.Collections.Generic.List<game.Value>();
    [global::ProtoBuf.ProtoMember(3, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<game.Value> values
    {
      get { return _values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ValueMap")]
  public partial class ValueMap : global::ProtoBuf.IExtensible
  {
    public ValueMap() {}
    
    private readonly global::System.Collections.Generic.List<game.ValuePair> _pairs = new global::System.Collections.Generic.List<game.ValuePair>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pairs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<game.ValuePair> pairs
    {
      get { return _pairs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRequest")]
  public partial class GameRequest : global::ProtoBuf.IExtensible
  {
    public GameRequest() {}
    
    private string _messageType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"messageType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string messageType
    {
      get { return _messageType; }
      set { _messageType = value; }
    }
    private readonly global::System.Collections.Generic.List<game.Value> _values = new global::System.Collections.Generic.List<game.Value>();
    [global::ProtoBuf.ProtoMember(2, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<game.Value> values
    {
      get { return _values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameReply")]
  public partial class GameReply : global::ProtoBuf.IExtensible
  {
    public GameReply() {}
    
    private string _messageType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"messageType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string messageType
    {
      get { return _messageType; }
      set { _messageType = value; }
    }
    private readonly global::System.Collections.Generic.List<game.Value> _values = new global::System.Collections.Generic.List<game.Value>();
    [global::ProtoBuf.ProtoMember(2, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<game.Value> values
    {
      get { return _values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}